server:
  port: 8761

eureka:
  server:
    #设置自我保护机制的阈值，默认0.85
    renewal-percent-threshold: 0.75
    #关闭自我保护机制，默认为true
    #enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false #指定当前主机是否需要向Eureka Server注册自己 false代表不注册
    fetch-registry: false #指定当前主机是否需要从Eureka Server下载服务注册表
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/