server:
  port: 8081

spring:
  #配置jpa
  jpa:
    generate-ddl: true #指定是否在spring启动时创建表 默认false
    show-sql: true #指定在控制台是否显示sql语句 默认false
    hibernate:
      ddl-auto: none #指定应用重启后不重新更新表内容

  #配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///kkb?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root

eureka:
  client:
    service-url:
      #指定当前client要连接的eureka server
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: provider-8081